### ISSUE TITLE
Zooming while moving mouse causes camera to drag with mouse movement

### ISSUE THREAD

**Issue by TheRealElysium** [FluffierThanThou/Fluffy_ZoomToMouse#1]
Feels a bit jarring when it happens, don't know if there is an easy fix.  Nice mod otherwise.

**Comment by FluffierThanThou** [comment]
Yeah, it's a known issue. Reason is slightly complicated, but it's basically because I compare mouse positions before and after zooming to calculate the offsets, instead of breaking into the actual zoom code (I tried that and ran into some buggy behaviour).

Let's just call it a feature, shall we? :D
